# Jupytext configuration file
# See https://jupytext.readthedocs.io/en/latest/config.html

# デフォルトのフォーマット設定
formats = "notebooks//ipynb,notebooks//py:percent"

# メタデータの保持
notebook_metadata_filter = "jupytext,language_info,execution_count"
cell_metadata_filter = "execution_count,execution_info"