version: '3'
services:
  ml:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=${JUPYTER_TOKEN}