version: '3'
services:
  ds:
    build:
      context: .
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    working_dir: /workspace
    tty: true
    stdin_open: true
