version: '3'
services:
  kaggle:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./code:/workspace
      - ~/.vscode-server:/home/kaggle/.vscode-server
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=${JUPYTER_TOKEN} --NotebookApp.password=${JUPYTER_PASSWORD}