version: '3.8'

services:
  ml:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    volumes:
      - .:/workspace:cached
    environment:
      - PYTHONPATH=/workspace
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - "8888:8888"
    user: "1000:1000"
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='${JUPYTER_TOKEN}' --NotebookApp.password='' --ServerApp.token='${JUPYTER_TOKEN}' --ServerApp.password=''"
