# 実験設定
name: titanic-experiment
description: "Titanic competition experiment with LightGBM"

# W&B設定
wandb:
  project: titanic
  entity: gen03
  tags:
    - titanic
    - classification
    - lightgbm

# 実験パラメータ
parameters:
  random_state: 42
  test_size: 0.2
  n_trials: 100
  model: lightgbm
  features:
    - Pclass
    - Sex
    - Age
    - SibSp
    - Parch
    - Fare
    - Embarked
  target: Survived

# 実験管理
logging:
  level: INFO
  save_model: true
  save_predictions: true
  save_feature_importance: true

# アンサンブル設定
ensemble:
  methods:
    - voting
    - stacking
  weights:
    - 0.6
    - 0.4