# モデル設定
name: lightgbm
params:
  objective: binary
  metric: binary_logloss
  boosting_type: gbdt
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  max_depth: 6
  min_data_in_leaf: 20
  lambda_l1: 0.1
  lambda_l2: 0.1

# 学習設定
train:
  n_splits: 5
  random_state: 42
  early_stopping_rounds: 100
  verbose: 100

# 評価設定
evaluation:
  metrics:
    - accuracy
    - auc
    - f1
  cv_strategy: stratified
